<a href="https://colab.research.google.com/github/Min-13/minist_digit_classification/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



1. Import TensorFlow



In [ ]:
# Import TensorFlow for building and training the neural network
import tensorflow as tf

2. Load MINIST Dataset

In [ ]:
# Load the MNIST dataset (handwritten digits 0–9)
# It automatically splits into training and testing sets
mnist = tf.keras.datasets.mnist

# X = images (28x28 grayscale), y = labels (0–9)
(X_train, y_train), (X_test, y_test) = mnist.load_data()

3. Inspect Dataset Shape

In [ ]:
# Check training image shape
# Expected: (60000, 28, 28)
X_train.shape

# Check training label shape
# Expected: (60000,)
y_train.shape

(60000,)

4. View a Sample Image (Raw Pixel Values)

In [ ]:
# Inspect first image (28x28 matrix of pixel values from 0–255)
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 170,
        253, 253, 253, 253, 253, 225, 172, 253, 242, 195,  64,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  49, 238, 253, 253, 253, 253,
        253, 253, 253, 253, 251,  93,  82,  82,  56,  39,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  18, 219, 253, 253, 253, 253,
        253, 198, 182, 247, 241,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  80, 156, 107, 253, 253,
        205,  11,   0,  43, 154,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14,   1, 154, 253,
         90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 139, 253,
        190,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11, 190,
        253,  70,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  35,
        241, 225, 160, 108,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         81, 240, 253, 253, 119,  25,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  45, 186, 253, 253, 150,  27,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  16,  93, 252, 253, 187,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 249, 253, 249,  64,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  46, 130, 183, 253, 253, 207,   2,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  39,
        148, 229, 253, 253, 253, 250, 182,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  24, 114, 221,
        253, 253, 253, 253, 201,  78,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  23,  66, 213, 253, 253,
        253, 253, 198,  81,   2,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  18, 171, 219, 253, 253, 253, 253,
        195,  80,   9,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,  55, 172, 226, 253, 253, 253, 253, 244, 133,
         11,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 136, 253, 25

5. Normalize Data

In [ ]:
# Normalize pixel values from range [0, 255] to [0, 1]
# This improves training stability and convergence
X_train, X_test = X_train / 255.0, X_test / 255.0

6. Build the Neural Network

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Input, Dropout

# Create a Sequential neural network model
model = Sequential()

# Define input shape (28x28 grayscale image)
model.add(Input(shape=(28, 28)))

# Flatten image into 784-dimensional vector
model.add(Flatten())

# Hidden layer with 128 neurons and ReLU activation
model.add(Dense(128, activation='relu'))

# Dropout layer to reduce overfitting (randomly disables 20% of neurons)
model.add(Dropout(0.2))

# Output layer with 10 neurons (one per digit class)
# No activation because we use logits (softmax applied later)
model.add(Dense(10))

7. Test Untrained Model (Sanity Check)

In [ ]:
# Generate prediction before training (random weights)
nonsense_prediction = model(X_train[:1]).numpy()

nonsense_prediction

array([[-0.6738222 , -0.29499793,  0.24961151, -1.3766518 ,  0.43270487,
        -0.3638906 ,  0.79943556,  0.6006336 , -0.30843014, -0.16356562]],
      dtype=float32)

8. Convert Logits to Probabilites

In [ ]:
# Apply softmax to convert logits to probability distribution
tf.nn.softmax(nonsense_prediction).numpy().sum()

np.float32(1.0)

9. Define Loss Function

In [ ]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy

# Use sparse categorical crossentropy
# from_logits=True because output layer does NOT use softmax
loss_fn = SparseCategoricalCrossentropy(from_logits=True)

# Compute initial loss (before training)
loss_fn(y_train[:1], nonsense_prediction)

<tf.Tensor: shape=(), dtype=float32, numpy=2.730191707611084>

10. Compile Model

In [ ]:
from tensorflow.keras.optimizers import Adam

# Use Adam optimizer with learning rate 0.01
optimizer = Adam(learning_rate=0.01)

# Compile model with optimizer, loss, and accuracy metric
model.compile(
    optimizer=optimizer,
    loss=loss_fn,
    metrics=['accuracy']
)

11. Train Model

In [ ]:
# Train for 10 epochs on training dataset
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8715 - loss: 0.4128
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9336 - loss: 0.2354
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9388 - loss: 0.2200
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9459 - loss: 0.2003
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9494 - loss: 0.1950
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9482 - loss: 0.2008
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9517 - loss: 0.1890
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9533 - loss: 0.1843
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9531 - loss: 0.1824
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9569 - loss: 0.1747


12. Evaluate Model

In [ ]:
# Evaluate performance on unseen test data
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9586 - loss: 0.2132


[0.19969598948955536, 0.9624999761581421]

13. Make Final Prediction

In [ ]:
# Convert model output to probabilities
tf.nn.softmax(model(X_test[:1])).numpy()

array([[0.0000000e+00, 1.6875105e-30, 2.4212334e-23, 4.2021700e-21,
        0.0000000e+00, 8.1730843e-28, 0.0000000e+00, 1.0000000e+00,
        1.1709460e-34, 6.7535652e-26]], dtype=float32)

In [ ]:
# Actual label
y_test[:1]

array([7], dtype=uint8)